"""
Individual Camera Worker Thread.
Runs a dedicated processing loop for a single camera feed, applying frame-skipping,
640x640 inference optimization, multi-object tracking, behavioral analytics,
and synchronizing alerts onto the shared AlertQueueManager.
"""

import cv2
import time
import logging
import threading
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List, Tuple
import numpy as np

from core.models import AlertEvent, PersonRecord
from core.virtual_fence import VirtualFence
from core.ingestion import RTSPStreamReader
from core.engine import FrameProcessingEngine
from db.queue_manager import AlertQueueManager
from db.supabase_client import SupabaseManager

logger = logging.getLogger(__name__)


class CameraWorkerThread:
    """
    Dedicated worker thread per camera stream.
    Synchronizes with the shared AlertQueueManager and provides thread-safe annotated frames for API streaming.
    """

    def __init__(
        self,
        config: Dict[str, Any],
        alert_queue: AlertQueueManager,
        supabase_manager: Optional[SupabaseManager] = None,
        yolo_model: str = "yolov8n.pt",
        device: str = "auto"
    ):
        self.config = config
        self.camera_id = config.get("id", "camera1")
        self.camera_name = config.get("name", f"Camera {self.camera_id}")
        self.rtsp_url = config.get("rtsp_url", "")
        self.fallback_file = config.get("fallback_file", "")
        self.location = config.get("location", "Border Sector")
        self.frame_skip = max(1, int(config.get("frame_skip", 2)))
        self.conf_threshold = float(config.get("conf_threshold", 0.25))
        self.target_size = tuple(config.get("target_inference_size", [640, 640]))
        self.alert_queue = alert_queue
        self.supabase_manager = supabase_manager or getattr(alert_queue, "supabase", None) or SupabaseManager()

        # Parse virtual fences
        fences: List[VirtualFence] = []
        for f_data in config.get("fences", []):
            coords = [tuple(pt) for pt in f_data.get("coordinates", [])]
            fences.append(VirtualFence(
                fence_id=f_data.get("id", f"fence_{self.camera_id}"),
                coordinates=coords,
                fence_type=f_data.get("type", "line"),
                name=f_data.get("name", "Boundary Zone"),
                position=f_data.get("position", 50.0)
            ))

        # Ingestion reader
        self.reader = RTSPStreamReader(rtsp_url=self.rtsp_url, camera_id=self.camera_id)

        # AI Engine instance
        self.engine = FrameProcessingEngine(
            camera_id=self.camera_id,
            camera_name=self.camera_name,
            location=self.location,
            fences=fences,
            enable_anpr=config.get("enable_anpr", True),
            enable_face_detection=config.get("enable_face_detection", True),
            enable_night_mode=config.get("enable_night_mode", True),
            yolo_model=yolo_model,
            conf_threshold=self.conf_threshold,
            device=device,
            supabase_manager=self.supabase_manager
        )

        # Configure asynchronous alert & POI callbacks from engine
        self.engine.set_alert_callback(self._on_async_alert)
        self.engine.set_person_callback(self._on_person_captured)

        # Threading & status
        self.is_running = False
        self.display_thread: Optional[threading.Thread] = None
        self.ai_thread: Optional[threading.Thread] = None
        self.lock = threading.Lock()
        
        # Frame and metrics buffers
        self.latest_annotated_frame: Optional[np.ndarray] = None
        self.latest_raw_frame: Optional[np.ndarray] = None
        self.frame_counter = 0
        self.processed_counter = 0
        self.fps = 0.0
        self.ai_fps = 0.0
        self.avg_inference_time_ms = 0.0
        self.last_metrics: Dict[str, Any] = {}
        self.total_alerts_generated = 0
        self.total_persons_captured = 0
        self.is_connected = False
        self._new_frame_event = threading.Event()
        self._latest_ai_input_frame: Optional[np.ndarray] = None
        self._latest_ai_timestamp: float = 0.0

    def _on_async_alert(self, alerts: List[AlertEvent], timestamp: float):
        """Callback for alerts generated by background worker threads (e.g. ANPR)."""
        if alerts:
            self.total_alerts_generated += len(alerts)
            self.alert_queue.push_alerts(alerts, current_time=timestamp)

    def _on_person_captured(self, person: PersonRecord):
        """Callback when a clear face / Person of Interest is identified."""
        self.total_persons_captured += 1
        logger.info(f"[{self.camera_id}] POI Captured: {person.person_id} ({person.name}) - Threat: {person.threat_level}")
        try:
            self.supabase_manager.insert_person(person)
        except Exception as e:
            logger.error(f"Error persisting Person of Interest: {e}")


    def start(self) -> "CameraWorkerThread":
        """Start the camera ingestion, display rendering, and AI inference worker threads."""
        if self.is_running:
            return self
        
        # Start ingestion reader
        self.reader.start()
        
        self.is_running = True
        
        # 1. Start dedicated AI worker thread (low latency, continuous background inference)
        self.ai_thread = threading.Thread(
            target=self._ai_inference_loop,
            name=f"CameraAI-{self.camera_id}",
            daemon=True
        )
        self.ai_thread.start()

        # 2. Start high-framerate real-time display and overlay loop
        self.display_thread = threading.Thread(
            target=self._display_loop,
            name=f"CameraDisplay-{self.camera_id}",
            daemon=True
        )
        self.display_thread.start()

        logger.info(f"[{self.camera_id}] CameraWorker threads started (Display + AI decoupled).")
        return self

    def _display_loop(self):
        """High-FPS real-time loop that reads fresh frames and applies HUD overlays instantly."""
        fps_start = time.perf_counter()
        fps_frames = 0
        last_frame_ts = 0.0

        while self.is_running:
            frame: Optional[np.ndarray] = None
            timestamp = time.time()

            if self.reader.is_connected:
                ret, frame, ts = self.reader.read()
                if ret and frame is not None:
                    timestamp = ts
                    self.is_connected = True
                else:
                    self.is_connected = False
            else:
                self.is_connected = False

            if frame is None or not self.is_connected:
                with self.lock:
                    self.latest_annotated_frame = None
                    self.latest_raw_frame = None
                    self.fps = 0.0
                time.sleep(0.04)
                continue

            # Only process if a new frame timestamp has arrived
            if timestamp == last_frame_ts:
                time.sleep(0.002)
                continue
            last_frame_ts = timestamp

            self.frame_counter += 1
            fps_frames += 1

            # Update latest AI input frame and notify AI inference worker
            self._latest_ai_input_frame = frame
            self._latest_ai_timestamp = timestamp
            self._new_frame_event.set()

            # Instantly render cached overlays onto the live frame (<1.5ms)
            annotated_frame = self.engine.render_hud_on_frame(frame)

            with self.lock:
                self.latest_annotated_frame = annotated_frame
                self.latest_raw_frame = frame

            now = time.perf_counter()
            elapsed = now - fps_start
            if elapsed >= 1.0:
                self.fps = round(fps_frames / elapsed, 1)
                fps_frames = 0
                fps_start = now

    def _ai_inference_loop(self):
        """Dedicated background AI worker that runs object detection and behavior analysis."""
        ai_fps_start = time.perf_counter()
        ai_frames = 0

        while self.is_running:
            # Wait until a fresh frame is ready
            signaled = self._new_frame_event.wait(timeout=0.2)
            if not self.is_running:
                break
            if not signaled:
                continue

            self._new_frame_event.clear()
            frame = self._latest_ai_input_frame
            timestamp = self._latest_ai_timestamp

            if frame is None or not self.is_connected:
                continue

            try:
                annotated_frame, new_alerts, metrics = self.engine.process_frame(frame, timestamp=timestamp)
                self.processed_counter += 1
                ai_frames += 1

                # Push alerts immediately to shared AlertQueueManager and Supabase
                if new_alerts:
                    self.total_alerts_generated += len(new_alerts)
                    self.alert_queue.push_alerts(new_alerts, current_time=timestamp)

                with self.lock:
                    self.last_metrics = metrics
                    self.avg_inference_time_ms = metrics.get("inference_time_ms", 0.0)

            except Exception as e:
                logger.error(f"[{self.camera_id}] Error in AI inference loop: {e}")

            now = time.perf_counter()
            elapsed = now - ai_fps_start
            if elapsed >= 1.0:
                self.ai_fps = round(ai_frames / elapsed, 1)
                ai_frames = 0
                ai_fps_start = now

    def get_latest_annotated_frame(self) -> Optional[np.ndarray]:
        """Thread-safe retrieval of latest annotated frame."""
        with self.lock:
            if self.latest_annotated_frame is None:
                return None
            return self.latest_annotated_frame.copy()

    def get_latest_raw_frame(self) -> Optional[np.ndarray]:
        """Thread-safe retrieval of pure, unannotated raw camera frame at native FPS."""
        with self.lock:
            if self.latest_raw_frame is not None:
                return self.latest_raw_frame.copy()
        if self.reader and self.reader.is_connected and self.reader.latest_frame is not None:
            return self.reader.latest_frame.copy()
        return None

    def get_active_suspects(self) -> List[Dict[str, Any]]:
        """Retrieve suspects actively visible in this camera feed right now.
        Returns data shaped like AlertEvent dicts so the frontend SuspectAlertModal can consume them directly.
        """
        now = time.time()
        suspects = []
        with self.lock:
            for track in self.engine.active_tracks:
                if track.class_name == "human" and track.matched_person_name:
                    prof_entry = self.engine.face_recognizer.known_profiles.get(track.matched_person_id, {})
                    db_img = prof_entry.get("image_url") or ""
                    db_dob = prof_entry.get("dob") or ""
                    db_notes = prof_entry.get("description") or ""

                    suspects.append({
                        # AlertEvent-compatible top-level fields
                        "id": f"live_{self.camera_id}_{track.track_id}",
                        "event_type": "face_detected",
                        "object_type": "human",
                        "camera_id": self.camera_id,
                        "camera_name": self.camera_name,
                        "location": self.location,
                        "confidence": 0.94,
                        "track_id": track.track_id,
                        "timestamp": datetime.now(timezone.utc).isoformat(),
                        "status": "new",
                        "details": f"Suspect Match: {track.matched_person_name}",
                        "image_path": f"/api/cameras/{self.camera_id}/snapshot?t={int(now)}",
                        "image_url": f"/api/cameras/{self.camera_id}/snapshot?t={int(now)}",
                        # Nested metadata — matches what SuspectAlertModal reads
                        "metadata": {
                            "matched_person": track.matched_person_name,
                            "person_id": track.matched_person_id or "",
                            "database_image_url": db_img,
                            "dob": db_dob,
                            "notes": db_notes,
                            "description": db_notes,
                            "similarity": 94.0,
                            "threat_level": "Critical Watchlist Match",
                            "status": "Recognized",
                        },
                        # Convenience flat fields for other consumers
                        "person_id": track.matched_person_id or "",
                        "person_name": track.matched_person_name,
                        "is_live": True,
                        "last_seen": now,
                    })
        return suspects

    def get_status(self) -> Dict[str, Any]:
        """Retrieve real-time camera telemetry and processing statistics."""
        with self.lock:
            return {
                "camera_id": self.camera_id,
                "camera_name": self.camera_name,
                "location": self.location,
                "ip_address": self.config.get("ip_address", ""),
                "rtsp_url": self.rtsp_url,
                "is_running": self.is_running,
                "is_connected": self.is_connected,
                "fps": self.fps,
                "ai_fps": self.ai_fps,
                "inference_time_ms": self.avg_inference_time_ms,
                "total_frames_read": self.frame_counter,
                "total_frames_processed": self.processed_counter,
                "total_alerts": self.total_alerts_generated,
                "active_tracks": len(self.engine.active_tracks),
                "is_night": self.engine.is_night,
                "scene_brightness": round(self.engine.night_enhancer.last_brightness, 1),
                "enable_face_detection": self.config.get("enable_face_detection", True),
                "enable_anpr": self.config.get("enable_anpr", True),
                "enable_night_mode": self.config.get("enable_night_mode", True),
                "conf_threshold": self.conf_threshold
            }

    def stop(self):
        """Stop worker and release camera stream."""
        self.is_running = False
        self._new_frame_event.set()
        if self.display_thread and self.display_thread.is_alive():
            self.display_thread.join(timeout=1.0)
        if self.ai_thread and self.ai_thread.is_alive():
            self.ai_thread.join(timeout=1.0)
        self.reader.stop()
        logger.info(f"[{self.camera_id}] CameraWorker stopped.")

